print("@@@@@@@    @@          @@      @@")
print("@@@@@@@    @@           @@    @@")
print("@@   @@    @@            @@  @@")
print("@@   @@    @@             @@@@")
print("@@   @@    @@              @@@               SCRAPER")
print("@@   @@    @@             @@ @@")
print("@@   @@    @@            @@   @@")
print("@@@@@@@    @@@@@@@      @@     @@")
print("@@@@@@@    @@@@@@@     @@       @@")
print("\n")
print("list untuk mengisi kategori yang bisa di scrap :")
print("Categories : mobil, properti, motor, keperluan-pribadi, elektronik-gadget, hobi-olahraga, rumah-tangga")
print("Categories : perlengkapan-bayi-anak, kantor-industri, jasa-lowongan-kerja")
print("Untuk kategori yang lebih spesifik tinggal di tambahkan (/) cth : properti/rumah dll ")
print("By : Greymonk aka 12f4ncndr")